// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPrhNythVwrmqyW6Xv87OgVGXAp9_6Ckk',
    appId: '1:938465830642:web:007b101b3fb2a1f66b526b',
    messagingSenderId: '938465830642',
    projectId: 'mambo-website-117d4',
    authDomain: 'mambo-website-117d4.firebaseapp.com',
    storageBucket: 'mambo-website-117d4.appspot.com',
    measurementId: 'G-HZ0W3N930P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOjeeC0620FKhWZyKr5jEMIZoHzJrEEgM',
    appId: '1:938465830642:android:4e16f29ce39619516b526b',
    messagingSenderId: '938465830642',
    projectId: 'mambo-website-117d4',
    storageBucket: 'mambo-website-117d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIIaD41vdarsFUhUrWRK9LdMeTRqQytI',
    appId: '1:938465830642:ios:19db7261612cc8d16b526b',
    messagingSenderId: '938465830642',
    projectId: 'mambo-website-117d4',
    storageBucket: 'mambo-website-117d4.appspot.com',
    iosBundleId: 'com.example.tugasArkom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlIIaD41vdarsFUhUrWRK9LdMeTRqQytI',
    appId: '1:938465830642:ios:a8202d04051e3b126b526b',
    messagingSenderId: '938465830642',
    projectId: 'mambo-website-117d4',
    storageBucket: 'mambo-website-117d4.appspot.com',
    iosBundleId: 'com.example.tugasArkom.RunnerTests',
  );
}
